Resources {
//Required
addTexture("UITextBox","Data/UI/TextBox.png");
addTexture("sprExclamation","Data/Sprites/Exclamation.png");
addTexture("sprPlayer","Data/Sprites/Charity.png");
addTexture("sprShadow","Data/Sprites/Shadow.png");
addFont(1,"Data/Fonts/STREET.ttf",19);

//Additional
addTexture("sprLeFleur","Data/Sprites/Charity.png");
addTexture("imgBook","Data/Images/Book.png");
addTexture("TileSet","Data/Tiles/TileSet.png");
addTexture("sprTable","Data/Sprites/Table.png");
};