Map {
function(Init);
//debug();
//setEffect(noise,1);
end();

function(Bed);
showText("Charity","I don't want to sleep.");
showText("Charity","At least now.");
end();

function(Table);
showText("Charity","My table. It's so old...");
end();

function(Nightstand);
showText("Charity","The nightstand is broken; the drawer doesn't want to open.");
showText("Charity","My dairy is stuck in there...");
end();
}